//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLocati.MediaData {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLocati.MediaData.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  (cache size: {0}).
        /// </summary>
        internal static string _cache_size_X_ {
            get {
                return ResourceManager.GetString("_cache_size_X_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (precision: {0}).
        /// </summary>
        internal static string _precision_is_X {
            get {
                return ResourceManager.GetString("_precision_is_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (precision not available).
        /// </summary>
        internal static string _precision_not_available {
            get {
                return ResourceManager.GetString("_precision_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file {0} is write-protected.
        ///Do you want to set it as writable?.
        /// </summary>
        internal static string Ask_remove_readonly_file_X {
            get {
                return ResourceManager.GetString("Ask_remove_readonly_file_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Asynchronous operation already running..
        /// </summary>
        internal static string Async_operation_already_running {
            get {
                return ResourceManager.GetString("Async_operation_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Automatic ({0}).
        /// </summary>
        internal static string AutomaticallyChooseLanguage_X {
            get {
                return ResourceManager.GetString("AutomaticallyChooseLanguage_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to change the metadata date/time to {0}?.
        /// </summary>
        internal static string Confirm_new_metadata_timestamp {
            get {
                return ResourceManager.GetString("Confirm_new_metadata_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to remove the position?.
        /// </summary>
        internal static string Confirm_remove_position {
            get {
                return ResourceManager.GetString("Confirm_remove_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to remove the date/time?.
        /// </summary>
        internal static string Confirm_remove_timestamp {
            get {
                return ResourceManager.GetString("Confirm_remove_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to normalize the video?.
        /// </summary>
        internal static string Confirm_video_normalization {
            get {
                return ResourceManager.GetString("Confirm_video_normalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to process file &quot;{0}&quot;..
        /// </summary>
        internal static string Failed_process_file_X {
            get {
                return ResourceManager.GetString("Failed_process_file_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FFprobe (part of FFmpeg).
        /// </summary>
        internal static string FFprobe_part_of_FFmpeg {
            get {
                return ResourceManager.GetString("FFprobe_part_of_FFmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to find the file
        ///{0}.
        /// </summary>
        internal static string File_not_found_X {
            get {
                return ResourceManager.GetString("File_not_found_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Altitude not supported
        ///for this kind of files.
        /// </summary>
        internal static string Filetype_dont_support_altitude {
            get {
                return ResourceManager.GetString("Filetype_dont_support_altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The following error occurred:
        ///{0}.
        /// </summary>
        internal static string Following_error_occurred_X {
            get {
                return ResourceManager.GetString("Following_error_occurred_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Global tag {0}.
        /// </summary>
        internal static string GlobalTag_X {
            get {
                return ResourceManager.GetString("GlobalTag_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - DarbAE Q2 2011 NAVTQ_ ng V5.
        /// </summary>
        internal static string GMapProvider_ArcGIS_DarbAE_Q2_2011_NAVTQ_Eng_V5_MapProvider {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_DarbAE_Q2_2011_NAVTQ_Eng_V5_MapProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - Imagery world 2D.
        /// </summary>
        internal static string GMapProvider_ArcGIS_Imagery_World_2D_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_Imagery_World_2D_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - Shaded relief world 2D.
        /// </summary>
        internal static string GMapProvider_ArcGIS_ShadedRelief_World_2D_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_ShadedRelief_World_2D_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - Street world 2D.
        /// </summary>
        internal static string GMapProvider_ArcGIS_StreetMap_World_2D_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_StreetMap_World_2D_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - Topo US 2D.
        /// </summary>
        internal static string GMapProvider_ArcGIS_Topo_US_2D_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_Topo_US_2D_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - World physical.
        /// </summary>
        internal static string GMapProvider_ArcGIS_World_Physical_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_World_Physical_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - World shaded relief.
        /// </summary>
        internal static string GMapProvider_ArcGIS_World_Shaded_Relief_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_World_Shaded_Relief_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - World street.
        /// </summary>
        internal static string GMapProvider_ArcGIS_World_Street_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_World_Street_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - World terrain.
        /// </summary>
        internal static string GMapProvider_ArcGIS_World_Terrain_Base_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_World_Terrain_Base_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ArcGIS - World topo.
        /// </summary>
        internal static string GMapProvider_ArcGIS_World_Topo_Map {
            get {
                return ResourceManager.GetString("GMapProvider_ArcGIS_World_Topo_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bing - Hybrid.
        /// </summary>
        internal static string GMapProvider_BingHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_BingHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bing.
        /// </summary>
        internal static string GMapProvider_BingMap {
            get {
                return ResourceManager.GetString("GMapProvider_BingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bing - Satellite.
        /// </summary>
        internal static string GMapProvider_BingSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_BingSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CloudMade - Demo.
        /// </summary>
        internal static string GMapProvider_CloudMade_Demo {
            get {
                return ResourceManager.GetString("GMapProvider_CloudMade_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Czech - History.
        /// </summary>
        internal static string GMapProvider_CzechHistoryMap {
            get {
                return ResourceManager.GetString("GMapProvider_CzechHistoryMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Czech - Hybrid.
        /// </summary>
        internal static string GMapProvider_CzechHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_CzechHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Czech.
        /// </summary>
        internal static string GMapProvider_CzechMap {
            get {
                return ResourceManager.GetString("GMapProvider_CzechMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Czech - Satellite.
        /// </summary>
        internal static string GMapProvider_CzechSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_CzechSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Czech - Turist.
        /// </summary>
        internal static string GMapProvider_CzechTuristMap {
            get {
                return ResourceManager.GetString("GMapProvider_CzechTuristMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google China - Hybrid.
        /// </summary>
        internal static string GMapProvider_GoogleChinaHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleChinaHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google China.
        /// </summary>
        internal static string GMapProvider_GoogleChinaMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleChinaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google China - Satellite.
        /// </summary>
        internal static string GMapProvider_GoogleChinaSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleChinaSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google China - Terrain.
        /// </summary>
        internal static string GMapProvider_GoogleChinaTerrainMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleChinaTerrainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google - Hybrid.
        /// </summary>
        internal static string GMapProvider_GoogleHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google Korea - Hybrid.
        /// </summary>
        internal static string GMapProvider_GoogleKoreaHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleKoreaHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google Korea.
        /// </summary>
        internal static string GMapProvider_GoogleKoreaMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleKoreaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google Korea - Satellite.
        /// </summary>
        internal static string GMapProvider_GoogleKoreaSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleKoreaSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google.
        /// </summary>
        internal static string GMapProvider_GoogleMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google - Satellite.
        /// </summary>
        internal static string GMapProvider_GoogleSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google - Terrain.
        /// </summary>
        internal static string GMapProvider_GoogleTerrainMap {
            get {
                return ResourceManager.GetString("GMapProvider_GoogleTerrainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Latvia.
        /// </summary>
        internal static string GMapProvider_LatviaMap {
            get {
                return ResourceManager.GetString("GMapProvider_LatviaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lithuania - 2.5D.
        /// </summary>
        internal static string GMapProvider_Lithuania_2_5d_Map {
            get {
                return ResourceManager.GetString("GMapProvider_Lithuania_2_5d_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lithuania - Hybrid.
        /// </summary>
        internal static string GMapProvider_LithuaniaHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_LithuaniaHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lithuania - Hybrid (old).
        /// </summary>
        internal static string GMapProvider_LithuaniaHybridMapOld {
            get {
                return ResourceManager.GetString("GMapProvider_LithuaniaHybridMapOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lithuania.
        /// </summary>
        internal static string GMapProvider_LithuaniaMap {
            get {
                return ResourceManager.GetString("GMapProvider_LithuaniaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lithuania - Ortho photo.
        /// </summary>
        internal static string GMapProvider_LithuaniaOrtoFotoMap {
            get {
                return ResourceManager.GetString("GMapProvider_LithuaniaOrtoFotoMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lithuania - Ortho photo (old).
        /// </summary>
        internal static string GMapProvider_LithuaniaOrtoFotoMapOld {
            get {
                return ResourceManager.GetString("GMapProvider_LithuaniaOrtoFotoMapOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lithuania - TOP50.
        /// </summary>
        internal static string GMapProvider_LithuaniaTOP50 {
            get {
                return ResourceManager.GetString("GMapProvider_LithuaniaTOP50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MapBender - WMS demo.
        /// </summary>
        internal static string GMapProvider_MapBender_WMS_demo {
            get {
                return ResourceManager.GetString("GMapProvider_MapBender_WMS_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Near - Hybrid.
        /// </summary>
        internal static string GMapProvider_NearHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_NearHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Near.
        /// </summary>
        internal static string GMapProvider_NearMap {
            get {
                return ResourceManager.GetString("GMapProvider_NearMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Near - Satellite.
        /// </summary>
        internal static string GMapProvider_NearSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_NearSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (none).
        /// </summary>
        internal static string GMapProvider_None {
            get {
                return ResourceManager.GetString("GMapProvider_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenCycle - Landscape.
        /// </summary>
        internal static string GMapProvider_OpenCycleLandscapeMap {
            get {
                return ResourceManager.GetString("GMapProvider_OpenCycleLandscapeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenCycle.
        /// </summary>
        internal static string GMapProvider_OpenCycleMap {
            get {
                return ResourceManager.GetString("GMapProvider_OpenCycleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenCycle - Transport.
        /// </summary>
        internal static string GMapProvider_OpenCycleTransportMap {
            get {
                return ResourceManager.GetString("GMapProvider_OpenCycleTransportMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenSea - Hybrid.
        /// </summary>
        internal static string GMapProvider_OpenSeaMapHybrid {
            get {
                return ResourceManager.GetString("GMapProvider_OpenSeaMapHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenStreetMap 4U.
        /// </summary>
        internal static string GMapProvider_OpenStreet4UMap {
            get {
                return ResourceManager.GetString("GMapProvider_OpenStreet4UMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenStreetMap.
        /// </summary>
        internal static string GMapProvider_OpenStreetMap {
            get {
                return ResourceManager.GetString("GMapProvider_OpenStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenStreetMap Quest.
        /// </summary>
        internal static string GMapProvider_OpenStreetMapQuest {
            get {
                return ResourceManager.GetString("GMapProvider_OpenStreetMapQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenStreetMap Quest - Hybrid.
        /// </summary>
        internal static string GMapProvider_OpenStreetMapQuestHybrid {
            get {
                return ResourceManager.GetString("GMapProvider_OpenStreetMapQuestHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenStreetMap Quest - Satellite.
        /// </summary>
        internal static string GMapProvider_OpenStreetMapQuestSattelite {
            get {
                return ResourceManager.GetString("GMapProvider_OpenStreetMapQuestSattelite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ovi - Hybrid.
        /// </summary>
        internal static string GMapProvider_OviHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_OviHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ovi.
        /// </summary>
        internal static string GMapProvider_OviMap {
            get {
                return ResourceManager.GetString("GMapProvider_OviMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ovi - Satellite.
        /// </summary>
        internal static string GMapProvider_OviSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_OviSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ovi - Terrain.
        /// </summary>
        internal static string GMapProvider_OviTerrainMap {
            get {
                return ResourceManager.GetString("GMapProvider_OviTerrainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spain.
        /// </summary>
        internal static string GMapProvider_SpainMap {
            get {
                return ResourceManager.GetString("GMapProvider_SpainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Turkey.
        /// </summary>
        internal static string GMapProvider_TurkeyMap {
            get {
                return ResourceManager.GetString("GMapProvider_TurkeyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a WikiMapia.
        /// </summary>
        internal static string GMapProvider_WikiMapiaMap {
            get {
                return ResourceManager.GetString("GMapProvider_WikiMapiaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yahoo - Hybrid.
        /// </summary>
        internal static string GMapProvider_YahooHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_YahooHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yahoo.
        /// </summary>
        internal static string GMapProvider_YahooMap {
            get {
                return ResourceManager.GetString("GMapProvider_YahooMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yahoo - Satellite.
        /// </summary>
        internal static string GMapProvider_YahooSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_YahooSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yandex - Hybrid.
        /// </summary>
        internal static string GMapProvider_YandexHybridMap {
            get {
                return ResourceManager.GetString("GMapProvider_YandexHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yandex.
        /// </summary>
        internal static string GMapProvider_YandexMap {
            get {
                return ResourceManager.GetString("GMapProvider_YandexMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yandex - Satellite.
        /// </summary>
        internal static string GMapProvider_YandexSatelliteMap {
            get {
                return ResourceManager.GetString("GMapProvider_YandexSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Google Elevation API did not complete the request (make sure you specified a valid API Key)..
        /// </summary>
        internal static string GoogleElevationRequest_denied {
            get {
                return ResourceManager.GetString("GoogleElevationRequest_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Google Elevation API request was malformed..
        /// </summary>
        internal static string GoogleElevationRequest_malformed {
            get {
                return ResourceManager.GetString("GoogleElevationRequest_malformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Google Elevation API reached the quota limit..
        /// </summary>
        internal static string GoogleElevationRequest_overquota {
            get {
                return ResourceManager.GetString("GoogleElevationRequest_overquota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS date without GPS time..
        /// </summary>
        internal static string GPS_date_without_time {
            get {
                return ResourceManager.GetString("GPS_date_without_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS tag.
        /// </summary>
        internal static string GPS_tag {
            get {
                return ResourceManager.GetString("GPS_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS time without GPS date..
        /// </summary>
        internal static string GPS_time_without_date {
            get {
                return ResourceManager.GetString("GPS_time_without_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Immagini.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Google Elevation API key is not valid..
        /// </summary>
        internal static string Invalid_Google_Elevation_API_Key {
            get {
                return ResourceManager.GetString("Invalid_Google_Elevation_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid response: missing &quot;{0}&quot; node..
        /// </summary>
        internal static string Invalid_response_missing_node_X {
            get {
                return ResourceManager.GetString("Invalid_response_missing_node_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid response: bad value of the &quot;{0}&quot; node (&quot;{1}&quot;)..
        /// </summary>
        internal static string Invalid_response_node_X_bad_value_Y {
            get {
                return ResourceManager.GetString("Invalid_response_node_X_bad_value_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid response: too many &quot;{0}&quot; nodes..
        /// </summary>
        internal static string Invalid_response_too_many_X_nodes {
            get {
                return ResourceManager.GetString("Invalid_response_too_many_X_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid value of tag &quot;{0}&quot; (&quot;{1}&quot;)..
        /// </summary>
        internal static string Invalid_tag_X_value_V {
            get {
                return ResourceManager.GetString("Invalid_tag_X_value_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No Google Elevation API key specified..
        /// </summary>
        internal static string Missing_Google_Elevation_API_Key {
            get {
                return ResourceManager.GetString("Missing_Google_Elevation_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This function requires the Google API Key to be set in the options window.
        ///Do you want to open it now?.
        /// </summary>
        internal static string Missing_Google_Elevation_API_Key_Ask_open_options {
            get {
                return ResourceManager.GetString("Missing_Google_Elevation_API_Key_Ask_open_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Missing latitude..
        /// </summary>
        internal static string Missing_latitude {
            get {
                return ResourceManager.GetString("Missing_latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Missing latitude reference..
        /// </summary>
        internal static string Missing_latituderef {
            get {
                return ResourceManager.GetString("Missing_latituderef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Missing longitude..
        /// </summary>
        internal static string Missing_longitude {
            get {
                return ResourceManager.GetString("Missing_longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Missing longitude reference..
        /// </summary>
        internal static string Missing_longituderef {
            get {
                return ResourceManager.GetString("Missing_longituderef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The {0} tool is missing.
        ///Do you want to download it now?
        ///
        ///PS: you should save it here:
        ///{1}.
        /// </summary>
        internal static string Missing_tool_message {
            get {
                return ResourceManager.GetString("Missing_tool_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Multiple GPS positions found..
        /// </summary>
        internal static string Multiple_GPS_positions_found {
            get {
                return ResourceManager.GetString("Multiple_GPS_positions_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Multiple tags &quot;{0}&quot; found..
        /// </summary>
        internal static string Multiple_tags_found {
            get {
                return ResourceManager.GetString("Multiple_tags_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No response from the server..
        /// </summary>
        internal static string No_server_response {
            get {
                return ResourceManager.GetString("No_server_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to find any video or audio track..
        /// </summary>
        internal static string No_video_audio {
            get {
                return ResourceManager.GetString("No_video_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Always.
        /// </summary>
        internal static string NormalizeCase_Always {
            get {
                return ResourceManager.GetString("NormalizeCase_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Always ask.
        /// </summary>
        internal static string NormalizeCase_AlwaysAsk {
            get {
                return ResourceManager.GetString("NormalizeCase_AlwaysAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Always on error.
        /// </summary>
        internal static string NormalizeCase_AlwaysOnError {
            get {
                return ResourceManager.GetString("NormalizeCase_AlwaysOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ask on error.
        /// </summary>
        internal static string NormalizeCase_AskOnError {
            get {
                return ResourceManager.GetString("NormalizeCase_AskOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Never.
        /// </summary>
        internal static string NormalizeCase_Never {
            get {
                return ResourceManager.GetString("NormalizeCase_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parsing folder {0}....
        /// </summary>
        internal static string Parsing_folder_X {
            get {
                return ResourceManager.GetString("Parsing_folder_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processing file {0}....
        /// </summary>
        internal static string Processing_file_X {
            get {
                return ResourceManager.GetString("Processing_file_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Program failed with exit code {0:N0}.
        /// </summary>
        internal static string Program_failed_with_returncode {
            get {
                return ResourceManager.GetString("Program_failed_with_returncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The retrieved elevation is wrong..
        /// </summary>
        internal static string Retrieved_elevation_wrong {
            get {
                return ResourceManager.GetString("Retrieved_elevation_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please select at least one map provider..
        /// </summary>
        internal static string Select_at_least_one_map_provider {
            get {
                return ResourceManager.GetString("Select_at_least_one_map_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the media source folder.
        /// </summary>
        internal static string Select_media_source_dir {
            get {
                return ResourceManager.GetString("Select_media_source_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Never.
        /// </summary>
        internal static string SetFileDates_Never {
            get {
                return ResourceManager.GetString("SetFileDates_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parsing source files and writing meta.
        /// </summary>
        internal static string SetFileDates_ReadingWriting {
            get {
                return ResourceManager.GetString("SetFileDates_ReadingWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a When writing meta data.
        /// </summary>
        internal static string SetFileDates_Writing {
            get {
                return ResourceManager.GetString("SetFileDates_Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} B.
        /// </summary>
        internal static string Size_bytes_X {
            get {
                return ResourceManager.GetString("Size_bytes_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} GB.
        /// </summary>
        internal static string Size_GB_X {
            get {
                return ResourceManager.GetString("Size_GB_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} KB.
        /// </summary>
        internal static string Size_KB_X {
            get {
                return ResourceManager.GetString("Size_KB_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} MB.
        /// </summary>
        internal static string Size_MB_X {
            get {
                return ResourceManager.GetString("Size_MB_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} TB.
        /// </summary>
        internal static string Size_TB_X {
            get {
                return ResourceManager.GetString("Size_TB_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stream tag {0}.
        /// </summary>
        internal static string StreamTag_X {
            get {
                return ResourceManager.GetString("StreamTag_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The system function &quot;{0}&quot; failed..
        /// </summary>
        internal static string System_function_X_failed {
            get {
                return ResourceManager.GetString("System_function_X_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tag {0}.
        /// </summary>
        internal static string Tag_X {
            get {
                return ResourceManager.GetString("Tag_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This Google Elevation API Key is valid..
        /// </summary>
        internal static string This_Google_Elevation_API_Key_good {
            get {
                return ResourceManager.GetString("This_Google_Elevation_API_Key_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It was not possible to set the new metadata..
        /// </summary>
        internal static string Unable_to_set_new_metadata {
            get {
                return ResourceManager.GetString("Unable_to_set_new_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to convert &quot;{0}&quot; to a position..
        /// </summary>
        internal static string Unable_to_unserialize_position_from_X {
            get {
                return ResourceManager.GetString("Unable_to_unserialize_position_from_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No processor found for files of type &quot;{0}&quot;..
        /// </summary>
        internal static string Unsupported_file_type_X {
            get {
                return ResourceManager.GetString("Unsupported_file_type_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unsupported stream type: &quot;{0}&quot;..
        /// </summary>
        internal static string Unsupported_stream_type_X {
            get {
                return ResourceManager.GetString("Unsupported_stream_type_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Video.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Videos (when transcoding).
        /// </summary>
        internal static string Videos_when_transcoding {
            get {
                return ResourceManager.GetString("Videos_when_transcoding", resourceCulture);
            }
        }
    }
}
